package com.example.apisecurity.ai;

public enum TestType { AUTHENTICATION, AUTHORIZATION, INPUT_VALIDATION, MISSING_REQUIRED_FIELD, INVALID_METHOD, BOUNDARY_VALUE, SECURITY_HEADERS, CONTENT_TYPE, RATE_LIMIT }
