import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import api from './api'

function Layout({ children }) {
  const navigate = useNavigate()
  const location = useLocation()
  const logout = () => { localStorage.removeItem('sentinel_token'); navigate('/login') }
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">S</span><span>Sentinel<span className="muted"> / API</span></span></div>
      <nav><Link className={location.pathname === '/' ? 'active' : ''} to="/">Overview</Link><Link className={location.pathname.startsWith('/projects') ? 'active' : ''} to="/projects">Projects</Link><Link to="/assistant">AI Assistant</Link></nav>
      <button className="logout" onClick={logout}>Sign out</button>
    </aside>
    <main className="main-content">{children}</main>
  </div>
}

function Login({ register = false }) {
  const navigate = useNavigate(); const [form, setForm] = useState({ username: '', password: '' }); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); try { const { data } = await api.post(`/auth/${register ? 'register' : 'login'}`, form); localStorage.setItem('sentinel_token', data.token); navigate('/') } catch (e) { setError(e.response?.data?.message || 'Unable to complete authentication') } }
  return <div className="auth-page"><div className="auth-card"><div className="brand"><span className="brand-mark">S</span><span>Sentinel API</span></div><p className="eyebrow">AUTHORIZED TESTING WORKSPACE</p><h1>{register ? 'Create your workspace' : 'Welcome back'}</h1><p className="muted">{register ? 'Register as a developer to begin testing APIs you own.' : 'Review evidence. Reduce risk. Ship with confidence.'}</p>{error && <div className="error">{error}</div>}<form onSubmit={submit}><label>Username<input required minLength="3" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button className="primary full">{register ? 'Create account' : 'Sign in'}</button></form><p className="auth-switch">{register ? 'Already registered?' : 'New to Sentinel?'} <Link to={register ? '/login' : '/register'}>{register ? 'Sign in' : 'Create an account'}</Link></p></div></div>
}

function Dashboard() { const [projects, setProjects] = useState([]); useEffect(() => { api.get('/projects').then(r => setProjects(r.data)).catch(() => {}) }, []); return <Layout><header className="page-header"><div><p className="eyebrow">SECURITY OPERATIONS</p><h1>Control room</h1><p className="muted">A clear view of your authorized API testing program.</p></div><Link className="primary" to="/projects/new">+ New project</Link></header><section className="metrics"><Metric label="Projects" value={projects.length}/><Metric label="Endpoints" value="—"/><Metric label="Tests passed" value="—"/><Metric label="Findings" value="—"/></section><section className="panel welcome-panel"><div><p className="eyebrow">SAFE BY DESIGN</p><h2>Start with an API you are authorized to test.</h2><p className="muted">Gemini proposes what to inspect. Java validates the plan and executes only predefined, non-destructive checks.</p><Link className="text-link" to="/projects">View registered projects →</Link></div><div className="signal">01<span>evidence first</span></div></section></Layout> }
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>current workspace</small></div> }

function Projects() { const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { api.get('/projects').then(r => setProjects(r.data)).catch(() => {}).finally(() => setLoading(false)) }, []); return <Layout><header className="page-header"><div><p className="eyebrow">INVENTORY</p><h1>Projects</h1><p className="muted">Registered targets and their testing boundaries.</p></div><Link className="primary" to="/projects/new">+ New project</Link></header>{loading ? <div className="panel">Loading projects...</div> : <div className="project-grid">{projects.map(p => <Link className="project-card" to={`/projects/${p.id}`} key={p.id}><div className="card-top"><span className="status-dot"/>ACTIVE</div><h2>{p.name}</h2><p className="muted">{p.description || 'No description yet.'}</p><div className="card-foot"><span>{p.baseUrl}</span><span>Open →</span></div></Link>)}{!projects.length && <div className="panel empty">No projects yet. Create your first authorized target.</div>}</div>}</Layout> }

function NewProject() { const navigate = useNavigate(); const [form, setForm] = useState({ name: '', description: '', baseUrl: 'http://localhost:8081' }); const [error, setError] = useState(''); const submit = async e => { e.preventDefault(); try { const { data } = await api.post('/projects', form); navigate(`/projects/${data.id}`) } catch (err) { setError(err.response?.data?.message || 'Unable to create project') } }; return <Layout><header className="page-header"><div><p className="eyebrow">PROJECT SETUP</p><h1>Register an API</h1><p className="muted">Only register a service you own or are authorized to test.</p></div></header><div className="panel form-panel">{error && <div className="error">{error}</div>}<form onSubmit={submit}><label>Project name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></label><label>Base URL<input required type="url" value={form.baseUrl} onChange={e => setForm({...form, baseUrl:e.target.value})}/><small>For this MVP, use localhost or a local network target.</small></label><label>Description<textarea value={form.description} onChange={e => setForm({...form, description:e.target.value})}/></label><button className="primary">Save project</button></form></div></Layout> }

function ProjectDetails() { const { pathname } = useLocation(); const id = pathname.split('/')[2]; const [project, setProject] = useState(null); const [endpoint, setEndpoint] = useState({ name:'', path:'', method:'GET', description:'', authenticationType:'NONE', expectedStatusCode:200 }); const [message, setMessage] = useState(''); useEffect(() => { api.get(`/projects/${id}`).then(r => setProject(r.data)).catch(() => {}) }, [id]); const add = async e => { e.preventDefault(); try { await api.post('/endpoints', { ...endpoint, projectId: id }); setMessage('Endpoint registered.'); setEndpoint({...endpoint, name:'', path:'', description:''}); const {data}=await api.get(`/projects/${id}`); setProject(data) } catch (err) { setMessage(err.response?.data?.message || 'Unable to register endpoint') } }; if (!project) return <Layout><div className="panel">Loading project...</div></Layout>; return <Layout><header className="page-header"><div><p className="eyebrow">PROJECT</p><h1>{project.name}</h1><p className="muted">{project.description} · {project.baseUrl}</p></div></header><div className="details-layout"><section><div className="section-heading"><h2>Registered endpoints</h2><span className="count">{project.endpoints?.length || 0}</span></div>{project.endpoints?.map(e => <div className="endpoint-row" key={e.id}><strong className="method">{e.method}</strong><div><h3>{e.path}</h3><p className="muted">{e.description || 'No description'}</p></div><span className="badge">{e.authenticationType}</span></div>)}{!project.endpoints?.length && <div className="panel empty">No endpoints registered yet.</div>}</section><section className="panel"><p className="eyebrow">BOUNDARY</p><h2>Add endpoint</h2>{message && <div className="notice">{message}</div>}<form onSubmit={add}><label>Name<input required value={endpoint.name} onChange={e=>setEndpoint({...endpoint,name:e.target.value})}/></label><label>Path<input required placeholder="/api/users" value={endpoint.path} onChange={e=>setEndpoint({...endpoint,path:e.target.value})}/></label><div className="form-row"><label>Method<select value={endpoint.method} onChange={e=>setEndpoint({...endpoint,method:e.target.value})}><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option><option>PATCH</option></select></label><label>Auth<select value={endpoint.authenticationType} onChange={e=>setEndpoint({...endpoint,authenticationType:e.target.value})}><option>NONE</option><option>JWT</option><option>API_KEY</option></select></label></div><label>Description<textarea value={endpoint.description} onChange={e=>setEndpoint({...endpoint,description:e.target.value})}/></label><button className="primary full">Register endpoint</button></form></section></div></Layout> }

function Assistant() { const [request,setRequest]=useState('Explain why an unauthenticated endpoint is risky.'); const [answer,setAnswer]=useState(''); const [busy,setBusy]=useState(false); const ask=async e=>{e.preventDefault();setBusy(true);try{const {data}=await api.post('/ai/chat',{question:request});setAnswer(data.answer)}catch(err){setAnswer(err.response?.data?.message||'AI assistant unavailable. Configure GEMINI_API_KEY on the backend.')}finally{setBusy(false)}}; return <Layout><header className="page-header"><div><p className="eyebrow">GEMINI ASSISTANT</p><h1>Ask about your evidence</h1><p className="muted">The assistant explains stored testing evidence. It never executes requests.</p></div></header><div className="panel chat-panel"><div className="chat-answer">{answer || <span className="muted">Your answer will appear here.</span>}</div><form onSubmit={ask}><textarea value={request} onChange={e=>setRequest(e.target.value)}/><button className="primary" disabled={busy}>{busy ? 'Thinking...' : 'Ask Gemini'}</button></form></div></Layout> }

function Protected({ children }) { return localStorage.getItem('sentinel_token') ? children : <Navigate to="/login" replace /> }
export default function App() { return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Login register/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/projects" element={<Protected><Projects/></Protected>}/><Route path="/projects/new" element={<Protected><NewProject/></Protected>}/><Route path="/projects/:id" element={<Protected><ProjectDetails/></Protected>}/><Route path="/assistant" element={<Protected><Assistant/></Protected>}/></Routes> }
