spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.model.chat.client.autoconfigure.ChatClientAutoConfiguration
  ai:
    model:
      chat: none
  datasource:
    url: jdbc:h2:mem:api_security;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080